language: python
python:
  - "3.6"
env:
  - CHAINER_VERSION=">=2.0" OPTIONAL_MODULES=1
sudo: false
dist: trusty

notifications:
    emails:
        - technext.jpn@gmail.com
    on_success: always
    on_failure: always

install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

  - if [[ "$OPTIONAL_MODULES" == "1" ]]; then
      conda env create -f environment.yml;
      source activate clib;
    fi
  - pip install -e .
  - pip install "chainer$CHAINER_VERSION"

script:
  - pwd
  - pip install flake8
  - pip install hacking
  - pip install autopep8
  - pip install mock
  - pip install py.test
  - make test
